language: scala

env:
 - SCALISMO_PLATFORM=linux64

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

before_cache:
  - rm -f $HOME/.ivy2/.*.lock $HOME/.ivy2/*.lock

scala:
  - 2.10.4
#  - 2.11.4

script:
  - jdk_switcher use oraclejdk8
  - sbt ++$TRAVIS_SCALA_VERSION -Djava.awt.headless=true compile test

